### ISSUE TITLE
Module build failed: TypeError: Must be an object

### ISSUE THREAD

**Issue by DavidDoesDev** [kisenka/webpack-svg-sprite-loader#4]
Great plugin! It was working perfectly for me one minute, and then suddenly it started throwing this warning and not compiling. I tried rolling back my code to see if it was something I changed. Unfortunately it's having the same issue in all previous commits (even the ones that I know were working). Do you know what the issue is? Any help appreciated.

**The Error**
``` bash
WARNING in ./~/svg-sprite-loader!./src/res/page-next.svg
Module build failed: TypeError: Must be an object
    at exports.objectToAttrString (/Users/dave/Dropbox/Sites/ProductStream/node_modules/svg-sprite-loader/lib/utils.js:6:11)
    at SVGDocument.toString (/Users/dave/Dropbox/Sites/ProductStream/node_modules/svg-sprite-loader/lib/svg-document.js:29:18)
    at Object.module.exports (/Users/dave/Dropbox/Sites/ProductStream/node_modules/svg-sprite-loader/index.js:47:17)
 @ ./src/res nonrecursive ./~/svg-sprite-loader!(page\-prev|page\-next)\.svg$

WARNING in ./~/svg-sprite-loader!./src/res/page-prev.svg
Module build failed: TypeError: Must be an object
    at exports.objectToAttrString (/Users/dave/Dropbox/Sites/ProductStream/node_modules/svg-sprite-loader/lib/utils.js:6:11)
    at SVGDocument.toString (/Users/dave/Dropbox/Sites/ProductStream/node_modules/svg-sprite-loader/lib/svg-document.js:29:18)
    at Object.module.exports (/Users/dave/Dropbox/Sites/ProductStream/node_modules/svg-sprite-loader/index.js:47:17)
 @ ./src/res nonrecursive ./~/svg-sprite-loader!(page\-prev|page\-next)\.svg$
```

**Main script (relevant parts)**
``` javascript
SVGs = require.context('svg-sprite!../res/', false, /(page\-prev|page\-next)\.svg$/);
SVGs.keys().forEach(SVGs);
```

**webpack.config.js**

``` javascript
module.exports = {
  entry: './src/index.js',
  output: {
    filename: './deploy/productstream.js'       
  },
  module: {
    loaders: [ // use ! to chain loaders
      { test: /\.html$/, loader: 'text-loader' },
      { test: /\.styl$/, loader: 'style-loader!css-loader!stylus-loader' },
      { test: /\.css$/, loader: 'style-loader!css-loader' },
      // {test: /\.(png|jpg)$/, loader: 'url-loader?limit=8192'} // inline base64 URLs for <=8k images, direct URLs for the rest
      {
        test: /\.svg$/,
        loader: 'svg-sprite?' + JSON.stringify({
          name: '[name]_[hash]',
          prefixize: true,
          spriteModule: 'utils/my-custom-sprite'
        })
      }
    ]
  },
  resolve: {
    extensions: ['', '.js', '.json', '.coffee']
  }
};
```

**Comment by kisenka** [comment]
Hi David!
You trying to process SVG files twice: first in Webpack config, and then in require statement.
Change your require expression to this: 
```js
SVGs = require.context('../res/', false, /(page\-prev|page\-next)\.svg$/);
```
Also you use `spriteModule` option in Webpack config. If you don't use custom sprite implementation I recommend do not use this option, because it specifies a path to custom sprite module, which you do not have.

**Comment by DavidDoesDev** [comment]
You're the man!

Ha! I even tried that while webpack was in the midst of `--watch`. Didn't realize you need to restart the process for the new config to take effect.
